fix: modify

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -91,21 +91,29 @@ jobs:
           fi
           echo "Will use image tag: ${{ env.IMAGE_TAG }}"
 
-      # - name: Configure AWS credentials
-      #   uses: aws-actions/configure-aws-credentials@v2
-      #   with:
-      #     aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
-      #     aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
-      #     aws-region: ${{ secrets.DEV_AWS_REGION }}
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.DEV_AWS_REGION }}
 
-      # - name: Log in to Amazon ECR
-      #   id: login-ecr
-      #   uses: aws-actions/amazon-ecr-login@v2
+      - name: Check if ECR Credential Helper is installed
+        run: which docker-credential-ecr-login || echo "ECR Credential Helper not found"
 
-      - name: Log in to Amazon ECR manually
+      - name: Set up Docker credential helper
         run: |
-          aws ecr get-login-password --region ap-southeast-1 | \
-          docker login --username AWS --password-stdin 681301424914.dkr.ecr.ap-southeast-1.amazonaws.com
+          mkdir -p ~/.docker
+          echo '{ "credHelpers": { "681301424914.dkr.ecr.ap-southeast-1.amazonaws.com": "ecr-login" } }' > ~/.docker/config.json
+
+      - name: Log in to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+      # - name: Log in to Amazon ECR manually
+      #   run: |
+      #     aws ecr get-login-password --region ap-southeast-1 | \
+      #     docker login --username AWS --password-stdin 681301424914.dkr.ecr.ap-southeast-1.amazonaws.com
 
       - name: Build and push Docker image
         run: |
